- name: Configurar Nginx proxy
  hosts: localhost
  gather_facts: false
  vars:
    project_root: "{{ playbook_dir }}/.."
    nginx_conf_host: "{{ project_root }}/host_volumes/nginx"
    web_root_host: "{{ project_root }}/host_volumes/web"
    nginx_container: "nginx"  # nombre del contenedor de Nginx

  tasks:
    - name: Crear directorios para volúmenes
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      loop:
        - "{{ nginx_conf_host }}"
        - "{{ web_root_host }}"

    - name: Copiar contenido web estático
      copy:
        src: "files/index.html"
        dest: "{{ web_root_host }}/index.html"
        mode: 0644

    - name: Copiar configuración de Nginx
      template:
        src: "templates/nginx.conf.j2"
        dest: "{{ nginx_conf_host }}/nginx.conf"
        mode: 0644

    - name: Intentar recargar Nginx
      command: "docker exec {{ nginx_container }} nginx -s reload"
      register: reload_result
      changed_when: reload_result.rc == 0
      ignore_errors: yes

    - name: Reiniciar contenedor si recarga falla
      command: "docker restart {{ nginx_container }}"
      when: reload_result.rc != 0